# Generated by Django 4.1 on 2022-08-13 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('egm', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componenta',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rezolutie',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('nr', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('informatorul', models.CharField(blank=True, max_length=200, null=True)),
                ('problema', models.TextField(blank=True, null=True)),
                ('solutie', models.CharField(blank=True, max_length=200, null=True)),
                ('sumar', models.CharField(blank=True, max_length=200, null=True)),
                ('responsabil', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('deschisa', 'Deschisa'), ('inchisa', 'Inchisa'), ('in_progres', 'In progres')], max_length=200)),
                ('data_inchidere', models.DateTimeField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('componenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.componenta')),
                ('egm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='egm.egm')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.label')),
                ('locatia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
                ('rezolutie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.rezolutie')),
            ],
        ),
    ]
