# Generated by Django 4.1 on 2022-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_options_alter_task_solutie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sumar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
