# Generated by Django 4.1 on 2022-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_componenta_id_alter_label_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_progres', 'Progres'), ('waiting_vnet', 'VNET'), ('waiting_cmac', 'CMAC'), ('waiting_lnm', 'LNM')], default='open', max_length=200),
        ),
    ]
