# Generated by Django 4.1 on 2022-09-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='egm',
            options={'ordering': ['serie']},
        ),
    ]
