# Generated by Django 4.1 on 2022-08-30 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='url_github',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_serviciu',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_serviciu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
