# Generated by Django 4.1 on 2022-09-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_email_serviciu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='functie',
            field=models.CharField(blank=True, default='Tehnician Electronica', max_length=200, null=True),
        ),
    ]
