# Generated by Django 4.1 on 2022-09-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_functie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_serviciu',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
